site_name: "test-repo-0"
site_description: ""
site_url: "https://.github.io/test-repo-0"
repo_url: "https://github.com//test-repo-0"
repo_name: "/test-repo-0"
site_dir: "site"
watch: [mkdocs.yml, ../src/test_repo_0]
copyright: Copyright &copy;  
edit_uri: edit/main/docs/

nav:
  - Home:
    - Readme: docs/index.md
    - API reference: reference/
    - Changelog: docs/changelog.md
    - Contributing: docs/contributing.md
    - Coverage report: coverage.md

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: purple
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  # font:
  #   text: Open Sans
  #   code: Fira Code
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow

extra_css:
- css/material.css
- css/mkdocstrings.css

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com//test-repo-0
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/test-repo-0/


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: docs
    url_download: true
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage:
    html_report_dir: ../htmlcov
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [src]
        options:
          docstring_style: null
          show_docstring_examples: false
          docstring_options:
            ignore_init_summary: false
          docstring_section_style: list
          trim_doctest_flags: true
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true

# - git-committers:
#     enabled: true
#     repository: /test-repo-0
# - git-revision-date-localized:
#     enable_creation_date: true
#     type: timeago
- minify:
    minify_html: true
- group:
    enabled: false
    plugins:
    - typeset
